from ...exceptions import ConnectorError


class VaultError(ConnectorError):
    pass
